## auth=oauth|apikey|signV4

## google/gemini-2.5-flash
google/gemini-2.5-flash.primary.provider=
google/gemini-2.5-flash.primary.model=google/gemini-2.5-flash
google/gemini-2.5-flash.primary.auth=oauth
google/gemini-2.5-flash.primary.hostname=aiplatform.googleapis.com
google/gemini-2.5-flash.primary.url=/v1/projects/apac-na-apigee-x-demo1/locations/global/endpoints/openapi/chat/completions

google/gemini-2.5-flash.fallback.provider=google
google/gemini-2.5-flash.fallback.model=google/gemini-2.5-flash
google/gemini-2.5-flash.fallback.auth=oauth
google/gemini-2.5-flash.fallback.hostname=us-east1-aiplatform.googleapis.com
google/gemini-2.5-flash.fallback.url=/v1beta1/projects/apac-na-apigee-x-demo1/locations/us-east1/endpoints/openapi/chat/completions


## google/gemini-3-flash-preview
google/gemini-3-flash-preview.primary.provider=google
google/gemini-3-flash-preview.primary.model=google/gemini-3-flash-preview
google/gemini-3-flash-preview.primary.auth=oauth
google/gemini-3-flash-preview.primary.hostname=aiplatform.googleapis.com
google/gemini-3-flash-preview.primary.url=/v1/projects/apac-na-apigee-x-demo1/locations/global/endpoints/openapi/chat/completions

google/gemini-3-flash-preview.fallback.provider=google
google/gemini-3-flash-preview.fallback.model=google/gemini-3-flash-preview
google/gemini-3-flash-preview.fallback.auth=oauth
google/gemini-3-flash-preview.fallback.hostname=aiplatform.googleapis.com
google/gemini-3-flash-preview.fallback.url=/v1/projects/apac-na-apigee-x-demo1/locations/global/endpoints/openapi/chat/completions


## google/gemini-3.1-pro-preview
google/gemini-3.1-pro-preview.primary.provider=google
google/gemini-3.1-pro-preview.primary.model=google/gemini-3.1-pro-preview
google/gemini-3.1-pro-preview.primary.auth=oauth
google/gemini-3.1-pro-preview.primary.hostname=aiplatform.googleapis.com
google/gemini-3.1-pro-preview.primary.url=/xxxv1/projects/apac-na-apigee-x-demo1/locations/global/endpoints/openapi/chat/completions

google/gemini-3.1-pro-preview.fallback.provider=azure
google/gemini-3.1-pro-preview.fallback.model=gpt-4.1-mini
google/gemini-3.1-pro-preview.fallback.auth=apikey
google/gemini-3.1-pro-preview.fallback.hostname=cbhong-eastus2.cognitiveservices.azure.com
google/gemini-3.1-pro-preview.fallback.url=/openai/deployments/gpt-4.1-mini/chat/completions?api-version=2025-01-01-preview
google/gemini-3.1-pro-preview.fallback.apikey=A1fSW7kYCt4gtC3yCNPyzPEBqSnF5HPWCcXfqyeCd0tDGdSvYtujJQQJ99BHACHYHv6XJ3w3AAAAACOG7aPv


## google/gemini-3.1-flash-lite-preview
google/gemini-3.1-flash-lite-preview.primary.provider=google
google/gemini-3.1-flash-lite-preview.primary.model=google/gemini-3.1-flash-lite-preview
google/gemini-3.1-flash-lite-preview.primary.auth=oauth
google/gemini-3.1-flash-lite-preview.primary.hostname=aiplatform.googleapis.com
google/gemini-3.1-flash-lite-preview.primary.url=/v1/projects/apac-na-apigee-x-demo1/locations/global/endpoints/openapi/chat/completions

google/gemini-3.1-flash-lite-preview.fallback.provider=azure
google/gemini-3.1-flash-lite-preview.fallback.model=gpt-4o-mini
google/gemini-3.1-flash-lite-preview.fallback.auth=apikey
google/gemini-3.1-flash-lite-preview.fallback.hostname=cbhong2-eastus2.cognitiveservices.azure.com
google/gemini-3.1-flash-lite-preview.fallback.url=/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview
google/gemini-3.1-flash-lite-preview.fallback.apikey=X2RD5kNxn1Q9ORjs4XWzTOxPqlELxjG7Gh6mbJOjnlU1yIdpyNpJJQQJ99CCACHYHv6XJ3w3AAAAACOGnnpg


## claude-sonnet-4-6
claude-sonnet-4-6.primary.provider=google
claude-sonnet-4-6.primary.model=claude-sonnet-4-6
claude-sonnet-4-6.primary.auth=oauth
claude-sonnet-4-6.primary.hostname=aiplatform.googleapis.com
claude-sonnet-4-6.primary.url=/v1/projects/apac-na-apigee-x-demo1/locations/global/publishers/anthropic/models/claude-sonnet-4-6:streamRawPredict

claude-sonnet-4-6.fallback.provider=google
claude-sonnet-4-6.fallback.model=claude-sonnet-4-6
claude-sonnet-4-6.fallback.auth=oauth
claude-sonnet-4-6.fallback.hostname=aiplatform.googleapis.com
claude-sonnet-4-6.fallback.url=/v1/projects/apac-na-apigee-x-demo1/locations/global/publishers/anthropic/models/claude-sonnet-4-6:streamRawPredict


## gpt-4.1-mini
gpt-4.1-mini.primary.provider=azure
gpt-4.1-mini.primary.model=gpt-4.1-mini
gpt-4.1-mini.primary.auth=apikey
gpt-4.1-mini.primary.hostname=cbhong-sweden.cognitiveservices.azure.com
gpt-4.1-mini.primary.url=/xxxopenai/deployments/gpt-4.1-mini/chat/completions?api-version=2025-01-01-preview
gpt-4.1-mini.primary.apikey=cmaFH9xaF3m97klk4TP3pWGxvAPsv6IsOOXKlgalkJdcfqQVpnfjJQQJ99BHACfhMk5XJ3w3AAAAACOGon5I
gpt-4.1-mini.primary.targeturl=https://cbhong-sweden.cognitiveservices.azure.com/openai/deployments/gpt-4.1-mini/chat/completions?api-version=2025-01-01-preview

gpt-4.1-mini.fallback.provider=google
gpt-4.1-mini.fallback.model=google/gemini-3-flash-preview
gpt-4.1-mini.fallback.auth=apikey
gpt-4.1-mini.fallback.hostname=aiplatform.googleapis.com
gpt-4.1-mini.fallback.url=/v1/projects/apac-na-apigee-x-demo1/locations/global/endpoints/openapi/chat/completions
gpt-4.1-mini.fallback.targeturl=https://aiplatform.googleapis.com/v1/projects/bap-payg01/locations/global/endpoints/openapi/chat/completions

## gpt-4o-mini
gpt-4o-mini.primary.provider=azure
gpt-4o-mini.primary.model=gpt-4o-mini
gpt-4o-mini.primary.auth=apikey
gpt-4o-mini.primary.hostname=cbhong2-eastus2.cognitiveservices.azure.com
gpt-4o-mini.primary.url=/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview
gpt-4o-mini.primary.apikey=X2RD5kNxn1Q9ORjs4XWzTOxPqlELxjG7Gh6mbJOjnlU1yIdpyNpJJQQJ99CCACHYHv6XJ3w3AAAAACOGnnpg
gpt-4o-mini.primary.targeturl=https://cbhong2-eastus2.cognitiveservices.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview

gpt-4o-mini.fallback.provider=azure
gpt-4o-mini.fallback.model=gpt-4o-mini
gpt-4o-mini.fallback.auth=apikey
gpt-4o-mini.fallback.hostname=cbhong2-sweden.cognitiveservices.azure.com
gpt-4o-mini.fallback.url=/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview
gpt-4o-mini.fallback.apikey=1FbScWJT1hLxvlSRh4Vx7YMw9CzNu1Zf91eP1N0YhrAjRNjHdHdwJQQJ99CCACfhMk5XJ3w3AAAAACOGWxk5
gpt-4o-mini.fallback.targeturl=https://cbhong2-sweden.cognitiveservices.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2025-01-01-preview


