#!/bin/bash
export PROJECT="YOUR_GCP_PROJECT_ID"
export APIGEE_ENV="YOUR_APIGEE_ENVIRONMENT"
export APIGEE_HOST="YOUR_APIGEE_HOST"
export CLIENT_SERVICE_ACCOUNT="YOUR_SERVICE_ACCOUNT_EMAIL"
export PROXY_SERVICE_ACCOUNT="YOUR_SERVICE_ACCOUNT_EMAIL"
export ROUTER_SERVICE_ACCOUNT="YOUR_SERVICE_ACCOUNT_EMAIL"
export PROXY_NAME="apigee-llm-gw-cr"
export REGION="us-central1"
